### ISSUE TITLE
%dim 2 is actually in dimension 3

### ISSUE THREAD

**Issue by coma94** [ilkka-torma/diddy#4]
When specifying dimension two after a topology grid, diddy somehow ends up in dimension 3.
For example 

```
%topology grid
%dim 2
%alphabet 0 1
%SFT goldenmean Ao (o = 1) -> (o.rt=0 & o.up=0)
%tiler goldenmean
```

raises the error

```Exception: Could not process transition rt from node (0, 0, 0)```

When doing it the other way around, or not specifying the dimension, everything works.

**Comment by ilkka-torma** [comment]
This is caused by `%dim` overwriting the topology, so that no edge named `rt` exists anymore. Also, the node `(0,0,0)` is not actually a 3D vector, but the 2D vector `(0,0)` bundled with the node named `0` (the only node name in the default environment).

This issue has been fixed as follows:
* Document the topology-rewriting behavior of `%dim`.
* Rename the default node from `0` to an unnamed node, internally represented as `()`.
* In general, rework the syntax for vectors containing nodes.
